---
- hosts: master
  become: yes
  tasks:
    - name: update dnf packages
      dnf:
        pkg: "*"
        state: latest
        update_cache: true
    - name: install basics Server
      dnf:
        pkg:
          - epel-release
          - curl
          - wget
          - vim
          - git
          - firewalld
          - zsh
          - tmux
        state: latest
        update_cache: true
    - name: Install prequisits for ansible
      dnf:
        pkg:
          - pipx
    - name: install ansible via pipx
      shell: pipx install --include-deps ansible
    - name: add current public key (~/.ssh/id_rsa.pub)
      ansible.posix.authorized_key:
        user: cloud
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
