---
- hosts: all
  become: true # makes the user root
  tasks:
    - name: Clone SCAP project
      git:
        repo: https://github.com/valerius21/scap.git
        dest: /tmp/scap
    - name: install libmagick
      apt:
        name:
          - ImageMagick-devel
      become: true
    - name: build scap
      command: go mod tidy && go build cmd/main.go && cp main ~/scap
      become: true
      args:
        chdir: /tmp/scap
