---
- hosts: all

  become: true # makes the user root

  tasks:
    - name: Install Packages
      dnf:
        pkg:
          - epel-release
          - curl
          - wget
          - vim
          - git
          - firewalld
          - zsh
          - tmux
        state: latest
        update_cache: true
    - name: add current public key (~/.ssh/id_rsa.pub)
      ansible.posix.authorized_key:
        user: cloud
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
