---
- hosts: all
  become: true # makes the user root
  tasks:
    - name: Install Packages
      dnf:
        name:
          - epel-release
          - curl
          - wget
          - vim
          - git
          - firewalld
          - zsh
          - tmux
        state: latest
        update_cache: true

    - name: add current public key (~/.ssh/id_rsa.pub)
      ansible.posix.authorized_key:
        user: cloud
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Add the docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install the needed packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Enable and start the Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Update SSH configuration (Change SSH Port)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port "
        line: "Port 10771"
      become: true

    - name: Restart SSH service
      ansible.builtin.service:
        name: sshd
        state: restarted
