---
- hosts: all

  become: true # makes the user root
  tasks:
    - name: update dnf packages
      dnf:
        pkg: "*"
        state: latest
        update_cache: true
    - name: Check for reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot the server if required
      ansible.buildin.reboot:
      when: reboot_required_file.stat.exists == true
