---
- hosts: all
  become: true # Makes the user root
  tasks:
    - name: Update dnf packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes
    - name: Check for reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
