---
- hosts: all

  become: true # makes the user root
  tasks:
    - name: update dnf packages
      dnf:
        pkg: "*"
        state: latest
    - name: Update and install required system packages
      dnf:
        pkg:
          - curl
          - vim
          - git
          - firewalld
        state: latest
        update_cache: true
